# -*- coding: utf-8 -*-
"""SQL_Codes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bcgvng9k4f5Yd3QRqoqoE994PEZCus_a
"""

# selecionando as colunas 'id, account_id, occurred_at' da tabela 'orders'
# SELECT id, account_id, occurred_at
# FROM orders

